#ifndef __CORE_H__
#define __CORE_H__
#include <stdint.h>

#define PERIPH_BASE (0x40000000UL)

// BUS
#define AHB1PERIPH_OFFSET (0x20000UL)
#define AHB1PERIPH_BASE (PERIPH_BASE + AHB1PERIPH_OFFSET)

#define APB1PERIPH_OFFSET (0x0000UL)
#define APB1PERIPH_BASE (PERIPH_BASE + APB1PERIPH_OFFSET)

// BUS AHB1
#define GPIOC_OFFSET (0x0800UL)
#define GPIOC_BASE (AHB1PERIPH_BASE + GPIOC_OFFSET)

#define GPIOB_OFFSET (0x0400UL)
#define GPIOB_BASE (AHB1PERIPH_BASE + GPIOB_OFFSET)

#define RCC_OFFSET (0x3800UL)
#define RCC_BASE (AHB1PERIPH_BASE + RCC_OFFSET)

// BUSS APB1
#define I2C1_OFFSET (0x5400UL)
#define I2C1_BASE (APB1PERIPH_BASE + I2C1_OFFSET)

#define I2C1EN (1U << 21)

// BUS AHB1 STRUCT

typedef struct
{
  volatile uint32_t DUMMY[12];
  volatile uint32_t AHB1ENR; // RCC AHB1 PERIPHERAL CLOCK REGISTER
  volatile uint32_t DUMMY2[3];
  volatile uint32_t APB1ENR; // RCC APB1 PERIPHERAL CLOCK ENABLE REGISTER

} RCC_TYPE;

#define RCC ((RCC_TYPE *)RCC_BASE)

// BUS APB1 STRUCT

// asm code
#define NOP() asm volatile("nop")

void delay(int time);

#endif /* __CORE_H__ */